name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ssh action
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }} # IP address of the server you wish to ssh into
        key: ${{ secrets.SSH_PRIVATE_KEY }} # Private or public key of the server
        username: ${{ secrets.SSH_USER }} # User of the server you want to ssh into
        port: ${{ secrets.SSH_PORT }}
        script: |
          sudo mkdir test # create folder you want to deploy to in the live server
          cd test # enter or cd into the folder
          sudo git clone https://github.com/sachinsachu96/test-repo.git
