name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: ssh action
      uses: appleboy/ssh-action@master
    
        script: |
          sudo mkdir test # create folder you want to deploy to in the live server
          cd test # enter or cd into the folder
          sudo git clone https://github.com/sachinsachu96/test-repo.git
